version: '3.8'

services:
  vue-frontend:
    build:
      context: ./nexus2-frontend          # Apunta a la carpeta del proyecto Vue
      dockerfile: ../docker/Dockerfile    # Dockerfile ubicado en la carpeta "docker"
    container_name: vue-frontend
    ports:
      - "3000:80"                         # El contenedor estará disponible en http://localhost:3000
    networks:
      - fastapi_nexus2                   # El nombre debe coincidir con el definido abajo
    environment:
      VUE_APP_BACKEND_URL: http://fastapi:8000 # URL del backend

networks:
  fastapi_nexus2:
    external: true                     # Usa la red externa